#!/usr/bin/env zsh

pushd $HOME/.dotfiles

STOW_FOLDERS=(zsh nvim tmux luaformatter xfce4-terminal gtk)

for folder in $STOW_FOLDERS; do
    echo $folder
    stow -D $folder
    stow $folder 
done

popd
