require('plugins')
require('options')
require('providers')
require('lsp_settings')
require('keymaps')

require('plugin_config.nvim_autopairs')
require('plugin_config.nvim_cmp')
require('plugin_config.nvim_treesitter')
require('plugin_config.telescope')
require('plugin_config.nvim_lspconfig')
require('plugin_config.nvim_tree')
require('plugin_config.bufferline')
require('plugin_config.auto_session')
require('plugin_config.zk_nvim')
