[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"

[scrolling]
history = 100000

[font]
size = 14
normal = { family = "Iosevka Nerd Font Mono", style = "Regular" }
bold = { family = "Iosevka Nerd Font Mono", style = "Bold" }
italic = { family = "Iosevka Nerd Font Mono", style = "Italic" }
bold_italic = { family = "Iosevka Nerd Font Mono", style = "Bold Italic" }

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]

[general]
import = ["~/.config/alacritty/themes/gruvbox.toml"]
